# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b81e573c321018d352d4998402105839ded5cb4a0375d50826952dbbd0fce63de0c7fb0900ba4d7dde52a6171aba83009353083665753414a543a952be5ad9a7

test:
  secret_key_base: bcbddff4451ae6a5b80515e0f6597c5c3509d593a777053396bd3507f8fe760f2831846ce7606b60d099a62956e98f527546901d9271a79cc94aedfe4d39858e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
